### ISSUE TITLE
Стабилизируй тесты

### ISSUE THREAD

**Issue by dveselov** [fidals/stroyprombeton#137]
Иногда тесты падают из-за того, что Selenium не успевает выполнить запрошенные действия, а django-тесты пытаются получить результат:
```
======================================================================
FAIL: test_new_entity_creation (stroyprombeton.tests.tests_selenium_admin.TableEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/drone/src/github.com/fidals/stroyprombeton/pull/135/stroyprombeton/tests/tests_selenium_admin.py", line 531, in test_new_entity_creation
    self.assertEqual(name_cell.get_attribute('title'), new_entity_text)
  File "/usr/local/lib/python3.6/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.6/unittest/case.py", line 1194, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/lib/python3.6/unittest/case.py", line 666, in fail
    raise self.failureException(msg)
AssertionError: 'A' != 'A New stuff'
- A
+ A New stuff
```
Артемий сделал тесты SE более-менее стабильными в https://github.com/fidals/shopelectro/pull/167, многие из них имеют общие части с STB. Поэтому можно посмотреть, что было сделано в SE для стабилизации тестов.

**Comment by 0pdd** [comment]
@dveselov 2 puzzles [#192](https://github.com/fidals/stroyprombeton/issues/192), [#193](https://github.com/fidals/stroyprombeton/issues/193) are still not solved; solved: [#191](https://github.com/fidals/stroyprombeton/issues/191).
