### ISSUE TITLE
Cart don't send mail

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#160]
Business wrote about it to Hellxi

**Comment by duker33** [comment]
stb-celery-mail-worker says, that `smtp.yandex.ru` don't what to auth us for mail sending.
Maybe it's because smtp port. In yandex's doc it differs from our config.

So, i'll move all mail settings to env

**Comment by duker33** [comment]
у mail'а всё ещё проблемы.

Celery очереди получают задачи, но они висят и не выполняются.

Воспроизводим на проде:
```
dcp exec stb-celery-mail-worker bash
celery -A stroyprombeton inspect active
```

вторая команда показывает, что у `worker.mail@%bc2b784fdb76: OK` четыре таски, которые висят и не выполняются.

Не шарю что с этим делать. Воркер вроде запущен, но ничего не хочет обрабатывать

**Comment by artemiy312** [comment]
@duker33 Возможно проблемы с названием queues/exchanges/routes

**Comment by artemiy312** [comment]
@duker33 
```
stb-celery-mail-worker       | [2018-01-13 23:25:17,056: ERROR/ForkPoolWorker-2] Task ecommerce.tasks.send_mail[c4527444-ba47-4d83-84f3-19526f760d4d] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed',)
stb-celery-mail-worker       | Traceback (most recent call last):
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
stb-celery-mail-worker       |     R = retval = fun(*args, **kwargs)
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
stb-celery-mail-worker       |     return self.run(*args, **kwargs)
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/ecommerce/tasks.py", line 8, in send_mail
stb-celery-mail-worker       |     django_send_mail(*args, **kwargs)
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 62, in send_mail
stb-celery-mail-worker       |     return mail.send()
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 342, in send
stb-celery-mail-worker       |     return self.get_connection(fail_silently).send_messages([self])
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
stb-celery-mail-worker       |     new_conn_created = self.open()
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 58, in open
stb-celery-mail-worker       |     self.connection = connection_class(self.host, self.port, **connection_params)
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
stb-celery-mail-worker       |     (code, msg) = self.connect(host, port)
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/smtplib.py", line 337, in connect
stb-celery-mail-worker       |     (code, msg) = self.getreply()
stb-celery-mail-worker       |   File "/usr/local/lib/python3.6/smtplib.py", line 393, in getreply
stb-celery-mail-worker       |     raise SMTPServerDisconnected("Connection unexpectedly closed")
stb-celery-mail-worker       | smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

**Comment by duker33** [comment]
@artemiy312 , воу, а я не мог добиться этого сообщения в логах. `stb-celery-mail-worker` просто говорил мне, что запустился и получил в работу пару тасков

**Comment by duker33** [comment]
@artemiy312 , вот какой лог вижу:
```
root@web:~/prog/stroyprombeton/docker# dcp logs stb-celery-mail-worker
Attaching to stb-celery-mail-worker
stb-celery-mail-worker       | /usr/local/lib/python3.6/site-packages/c                                                                          elery/platforms.py:795: RuntimeWarning: You're running the worker with                                                                           superuser privileges: this is
stb-celery-mail-worker       | absolutely not recommended!
stb-celery-mail-worker       |
stb-celery-mail-worker       | Please specify a different user using th                                                                          e -u option.
stb-celery-mail-worker       |
stb-celery-mail-worker       | User information: uid=0 euid=0 gid=0 egi                                                                          d=0
stb-celery-mail-worker       |
stb-celery-mail-worker       |   uid=uid, euid=euid, gid=gid, egid=egid                                                                          ,
stb-celery-mail-worker       | [2018-01-15 10:39:56,756: INFO/MainProce                                                                          ss] Connected to amqp://stb_rabbitmq:**@stb-rabbitmq:5672//
stb-celery-mail-worker       | [2018-01-15 10:39:56,783: INFO/MainProce                                                                          ss] mingle: searching for neighbors
stb-celery-mail-worker       | [2018-01-15 10:39:57,865: INFO/MainProce                                                                          ss] mingle: sync with 1 nodes
stb-celery-mail-worker       | [2018-01-15 10:39:57,868: INFO/MainProce                                                                          ss] mingle: sync complete
stb-celery-mail-worker       | [2018-01-15 10:39:57,920: INFO/MainProce                                                                          ss] worker.mail@%ebfaef79bd54 ready.
stb-celery-mail-worker       | [2018-01-15 10:39:57,922: INFO/MainProce                                                                          ss] Received task: ecommerce.tasks.send_mail[4735f25b-6545-4fb0-96a5-f9                                                                          ec8e3297be]
```

**Comment by artemiy312** [comment]
@duker33  
у yandex smtp изменился port?  -EMAIL_PORT = 587 +EMAIL_PORT = 465

**Comment by duker33** [comment]
@artemiy312 , да, сменился. Я его тоже сменил в .env+base.py

**Comment by artemiy312** [comment]
>artemiy312 , вот какой лог вижу:

я перезапустил воркер

**Comment by duker33** [comment]
@artemiy312 , ноуп, не взлетело, письма никуда не пришли

**Comment by artemiy312** [comment]
deployed

**Comment by duker33** [comment]
now it works!
![image](https://user-images.githubusercontent.com/3526796/34982991-21636bbe-fabd-11e7-84da-4e105e30ddba.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#162](https://github.com/fidals/stroyprombeton/issues/162) is still not solved; solved: [#163](https://github.com/fidals/stroyprombeton/issues/163).
