### ISSUE TITLE
Fix 502 errors from scan

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#334]
It's SE task, not STB. But i'll leave it because of created comments

Example link:
https://www.shopelectro.ru/catalog/categories/promyshlennye-3-7-v-li-pol-prizmaticheskie/tags/robiton/

Full list of links - in pinned docs.
This two docs orign from the same scan repeated twice:
[www.shopelectro.ru_Битые-ссылки_2.xlsx](https://github.com/fidals/stroyprombeton/files/2575923/www.shopelectro.ru_.-._2.xlsx)
[www.shopelectro.ru_Битые-ссылки.xlsx](https://github.com/fidals/stroyprombeton/files/2575924/www.shopelectro.ru_.-.xlsx)

**Comment by duker33** [comment]
we have link from body in search results:
https://www.shopelectro.ru/search/?term=%D0%BF%D1%80%D0%BE%D0%BC%D1%8B%D1%88%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5+3.7%D0%92

**Comment by duker33** [comment]
found this error in log. But seems it's not relevant for our situation:
```
Exception raised while rendering {% include %} for template 'catalog/category.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 59, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 137, in _render
    thumbnail = get_thumbnail(file_, geometry, **options)
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
    return default.backend.get_thumbnail(file_, geometry_string, **options)
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/base.py", line 135, in get_thumbnail
    default.kvstore.set(thumbnail, source)
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/kvstores/base.py", line 33, in set
    image_file.set_size()  # make sure its got a size
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/images.py", line 127, in set_size
    image = default.engine.get_image(self)
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/engines/pil_engine.py", line 49, in get_image
    return Image.open(buffer)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f279464b0a0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context.new(values))
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 66, in render
    if settings.TEMPLATE_DEBUG:
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_DEBUG'
```

**Comment by duker33** [comment]
and more relevant error from our nginx container:
```
se-nginx                 | 2018/11/27 12:45:17 [error] 9#9: *165518 upstream prematurely closed
connection while reading response header from upstream, client: 172.29.0.1, server: , request: "GET /ca
talog/categories/promyshlennye-3-7-v-li-pol-prizmaticheskie/ HTTP/1.0", upstream: "http://172.29.0.2:80
00/catalog/categories/promyshlennye-3-7-v-li-pol-prizmaticheskie/", host: "www.shopelectro.ru", referre
r: "https://www.shopelectro.ru/search/?term=%D0%BF%D1%80%D0%BE%D0%BC%D1%8B%D1%88%D0%BB%D0%B5%D0%BD%D0%B
D%D1%8B%D0%B5+3.7%D0%92"
```

**Comment by duker33** [comment]
hm, seems error disappeared.
I flushed django_session db table - that's all i've done.
Error don't appears on local machine too

**Comment by duker33** [comment]
it disappeared only for link http://127.0.0.1:8010/catalog/categories/novogodnie-lazernye-proektory-209/, but not for link from task body

**Comment by duker33** [comment]
django.template.base.Template.render() method leads app to exit with 0 because of this template's seo_text field:
https://www.shopelectro.ru/admin/pages/pagetemplate/15/change/

I localized this bug. The next task is to debug template
