### ISSUE TITLE
Fix price list generation

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#481]
Fix price list generation http://www.stroyprombeton.ru/gbi/categories/14275/pdf/

**Comment by artemiy312** [comment]
```
stb-python        | xvfb-run: error: Xvfb failed to start
stb-python        | Internal Server Error: /gbi/categories/14275/pdf/
stb-python        | Traceback (most recent call last):
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
stb-python        |     response = get_response(request)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
stb-python        |     response = self.process_exception_by_middleware(e, request)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
stb-python        |     response = response.render()
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 107, in render
stb-python        |     self.content = self.rendered_content
stb-python        |   File "/usr/local/lib/python3.6/site-packages/wkhtmltopdf/views.py", line 80, in rendered_content
stb-python        |     cover_template=self.resolve_template(self.cover_template)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/wkhtmltopdf/utils.py", line 237, in render_pdf_from_template
stb-python        |     cover_filename=cover.filename if cover else None)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/wkhtmltopdf/utils.py", line 166, in convert_to_pdf
stb-python        |     return wkhtmltopdf(pages=pages, **cmd_options)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/wkhtmltopdf/utils.py", line 147, in wkhtmltopdf
stb-python        |     return check_output(ck_args, **ck_kwargs)
stb-python        |   File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
stb-python        |     **kwargs).stdout
stb-python        |   File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
stb-python        |     output=stdout, stderr=stderr)
stb-python        | subprocess.CalledProcessError: Command '['xvfb-run', 'wkhtmltopdf', '--encoding', 'utf8', '--quiet', '/tmp/wkhtmltopdfw3ktnm11.html', '-']' returned non-zero exit status 1.
```

**Comment by artemiy312** [comment]
Revert `fidals/stb:prdo` to 0952c2b625b5 docker image and restart the prod. I'll count it as astronomical hours
