### ISSUE TITLE
Category admin page on the prod returns 500 

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#657]
https://www.stroyprombeton.ru/admin/stroyprombeton/categorypage/

some traceback parts for the prod:
```
stb-python        | Traceback (most recent call last):
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 617, in get_field
stb-python        |     return self.fields_map[field_name]
stb-python        | KeyError: 'model_id'
...
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 283, in lookup_field
stb-python        |     f = _get_non_gfk_field(opts, name)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 317, in _get_non_gfk_field
stb-python        |     field = opts.get_field(name)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 619, in get_field
stb-python        |     raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
stb-python        | django.core.exceptions.FieldDoesNotExist: CategoryPage has no field named 'model_id'

...
stb-python        |     f, attr, value = lookup_field(field_name, result, cl.model_admin)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 295, in lookup_field
stb-python        |     value = attr(obj)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/generic_admin/models.py", line 143, in model_id
stb-python        |     return super(CategoryPageAdmin, self).model_id(obj)
stb-python        |   File "/usr/local/lib/python3.6/site-packages/generic_admin/mixins.py", line 167, in model_id
stb-python        |     return obj.model.id
stb-python        | AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by duker33** [comment]
can't reproduce the error on a local app. So it's about categories data

**Comment by duker33** [comment]
seems DB has some problem pages:
```
(
	Page.objects
	.filter(related_model_name='stroyprombeton_category')
	.filter(stroyprombeton_category=None)
).count()
138
```

I'll expore if we can just rm them without data loss.

It's task about prod DB, so i'll log this exploration as astronomical hours

**Comment by duker33** [comment]
some of orphan category pages has images. So we should delete them carefully
```
>>> from images.models import Image
>>> from pages.models import Page
>>> from django.db.models import Subquery, OuterRef, Count
>>>
>>> (
...     Page.objects
...     .filter(related_model_name='stroyprombeton_category')
...     .filter(stroyprombeton_category=None)
ges')).values('id'))))t=Count(Subquery(Image.objects.filter(id__in=OuterRef('imag
...     .filter(count__gt=0)
... ).count()
70
```

**Comment by duker33** [comment]
most of them are ex series categories:
```
>>> (
...     Page.objects
...     .filter(related_model_name='stroyprombeton_category')
...     .filter(stroyprombeton_category=None)
...     .filter(name__icontains='серия')
... ).count()
134
```

**Comment by duker33** [comment]
launched this script on the prod:
```
from images.models import Image
from pages.models import Page
from django.db.models import Subquery, OuterRef, Count, Q
from stroyprombeton.models import Series


class Strategy:
    def __init__(self, qs):
        self.qs = qs
    @property
    def log_group(self):
        return f'{self.qs[0].name} {self.qs.values_list("id", flat=True)}'
    def merge(self, field):
        ...


class StackImages(Strategy):
    def merge(self, field):
        assert field == 'images'
        return Image.objects.filter(
            id__in=self.qs.values_list(field, flat=True)
        )

		
class StackTexts(Strategy):
    def merge(self, field):
        return '<br><br>'.join([v for v in self.qs.values_list(field, flat=True) if v])


to_delete = []
strange_series = {}
for series in Series.objects.all():
	pages = (
		Page.objects
		.filter(related_model_name='stroyprombeton_category')
		.filter(stroyprombeton_category=None)
		.filter(name__contains=series.name)
	)
	series.page.content = StackTexts(pages).merge('content')
	series.page.images.set(StackImages(pages).merge('images'))
	series.page.save()
	for page in pages:
		page.images.set([])
		# page.level, page.rght = 0, 0
		# page.parent = None
		page.save()
		to_delete.append(page.id)

Page.objects.filter(id__in=to_delete).delete()
```

**Comment by duker33** [comment]
categories list the admin (see the link at the task's body) working now.
Task is ready

spent 3 astro hours totally
