### ISSUE TITLE
Problems on commands queue starting on production

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#728]
Traceback from prod. Happens most of the times during `make deploy`

```
stb-python        | [2019-07-07 11:25:47 +0000] [1] [INFO] Starting gunicorn 19.9.0
stb-python        | SystemCheckError: System check identified some issues:
stb-python        |
stb-python        | ERRORS:
stb-python        | <unbound Queue command -> <unbound Exchange utils(direct)> -> utils.command>: Worker for the queuesn't available.
stb-python        |     HINT: Run a worker for the queue before launching the application.
stb-python        | <unbound Queue default -> <unbound Exchange default(direct)> -> default>: Worker for the queue isn available.
stb-python        |     HINT: Run a worker for the queue before launching the application.
stb-python        | <unbound Queue mail -> <unbound Exchange utils(direct)> -> utils.mail>: Worker for the queue isn'tvailable.
stb-python        |     HINT: Run a worker for the queue before launching the application.
stb-python        |
stb-python        | System check identified 3 issues (0 silenced).
stb-python        | Traceback (most recent call last):
stb-python        |   File "/usr/local/bin/gunicorn", line 11, in <module>
stb-python        |     sys.exit(run())
stb-python        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
stb-python        |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
stb-python        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
stb-python        |     super(Application, self).run()
stb-python        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
stb-python        |     Arbiter(self).run()
stb-python        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 199, in run
stb-python        |     self.start()
stb-python        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 140, in start
stb-python        |     self.cfg.on_starting(self)
stb-python        |   File "/etc/gunicorn.py", line 15, in on_starting
stb-python        |     subprocess.run(['python', 'manage.py', 'check'], check=True)
stb-python        |   File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
stb-python        |     output=stdout, stderr=stderr)
stb-python        | subprocess.CalledProcessError: Command '['python', 'manage.py', 'check']' returned non-zero exit stus 1.
```

**Comment by artemiy312** [comment]
I'll try follow the hints

**Comment by artemiy312** [comment]
The prod is running, so is nothing here to do

**Comment by artemiy312** [comment]
The docker should just restart the application after it has received errors. I'll test it

**Comment by artemiy312** [comment]
```
stb-python        | [2019-07-07 11:26:05 +0000] [1] [INFO] Starting gunicorn 19.9.0
stb-python        | SystemCheckError: System check identified some issues:
stb-python        |
stb-python        | ERRORS: ...
stb-python        | [2019-07-07 11:26:10 +0000] [1] [INFO] Starting gunicorn 19.9.0
```

It seems that Docker does what we expect and restarts the application after errors occur.

**Comment by artemiy312** [comment]
It is nothing wrong with these system check errors. The celery workers are required for prod runtime, so the check forces the deployer to start workers before the app. 

`make deploy` ups containers simultaneously and it seems the app container is done before celery, therefore errors occur.  

@duker33 Should I add few words about it to a error's messages?

**Comment by duker33** [comment]
@artemiy312 , this behavior leads the whole `make deploy` command to fail.
And the app docker service (production) depends on celery queue worker services. That's why i treat failed check behavior as unexpected.
```
# docker-compose-production.yml
app:
    ...
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - celery-mail
      - celery-default
      - celery-command
```

Imho we should prevent such check errors somehow. Any error in the log is not ok, i believe.

**Comment by artemiy312** [comment]
@duker33 , Oh, I see the point. `deploy` receipt fails, because system check errors restart a container during `deploy` is executing something inside

**Comment by artemiy312** [comment]
`depends_on` can't help us, because it doesn't know when a running process will ready to serve, so we have to use different approaches(e.g. `wait-for.sh`) to sync it

**Comment by duker33** [comment]
@artemiy312 , seems we have to do it or smth like. Now we've gotten deploy overhead and 15-30 mins of downtime on every deploy

**Comment by artemiy312** [comment]
@duker33 I'd prefer simply drop this rude system check, because now we have Sentry which informs us about any issues with workers
